# **SPRINT 10**
## APIs REST

### Importamos la librería request para poder hacer peticiones a una API

In [48]:
import requests
import pandas as pd

**Nivell 1**

Se crea una variable con la dirección url que vamos a usar

In [49]:
url_api = "https://jsonplaceholder.typicode.com"

Con .get hacemos la primera petición. En este caso, pedimos la lista de todas las publicaciones.

In [50]:
#Lista de posts

respuesta_posts = requests.get(url_api + "/posts")

Comprobamos el código del estado, depende del número que salga puede darnos error, en este caso es 200, lo que significa que la peticion ha ido bien.

In [51]:
respuesta_posts.status_code

200

Cuando hacemos una petición a una API, devuelve los datos en formato JSON. Para que Python trabaje mejor con los datos, convertimos la respuesta en objetivos de Python, así resultatá más fácil manipularlos.

In [52]:
posts = respuesta_posts.json()

In [53]:
print("Código de estado:", respuesta_posts.status_code)
print("Total de publicaciones:", len(posts))

Código de estado: 200
Total de publicaciones: 100

In [54]:
df_posts = pd.DataFrame(posts)

df_posts

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

Hacemos lo mismo para usuarios

In [55]:
#Lista usuarios

respuesta_users = requests.get(url_api + "/users")

respuesta_users.status_code

users = respuesta_users.json()

print("Código de estado:", respuesta_users.status_code)
print("Total de usuarios:", len(users))

Código de estado: 200
Total de usuarios: 10

In [56]:
df_users = pd.DataFrame(users)

df_users

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [57]:
#Lista tareas

respuesta_todos = requests.get(url_api + "/todos")

respuesta_todos.status_code

todos = respuesta_todos.json()

print("Código de estado:", respuesta_todos.status_code)
print("Total de tareas:", len(todos))

Código de estado: 200
Total de tareas: 200

In [58]:
df_todos = pd.DataFrame(todos)

df_todos

     userId   id                                              title  completed
0         1    1                                 delectus aut autem      False
1         1    2                 quis ut nam facilis et officia qui      False
2         1    3                                fugiat veniam minus      False
3         1    4                                   et porro tempora       True
4         1    5  laboriosam mollitia et enim quasi adipisci qui...      False
..      ...  ...                                                ...        ...
195      10  196                consequuntur aut ut fugit similique       True
196      10  197                  dignissimos quo nobis earum saepe       True
197      10  198                       quis eius est sint explicabo       True
198      10  199                       numquam repellendus a magnam       True
199      10  200                       ipsam aperiam voluptates qui      False

[200 rows x 4 columns]

### Cantitadad total cada recurso

In [59]:
print("POSTS")
print("Código:", respuesta_posts.status_code)
print("Total:", len(posts))

print("\nUSERS")
print("Código:", respuesta_users.status_code)
print("Total:", len(users))

print("\nTODOS")
print("Código:", respuesta_todos.status_code)
print("Total:", len(todos))

POSTS
Código: 200
Total: 100

USERS
Código: 200
Total: 10

TODOS
Código: 200
Total: 200

### Error 404

En la anterior parte del ejercicio hemos visto que hay 100 post, entonces para hacer la petición de un post que nos dé error tendremos que hacer un post que no exista, por ejemplo el 101.

In [60]:
post_error = requests.get(url_api + "/posts/101")

In [61]:
print(f'El código de estado: {post_error.status_code}')

El código de estado: 404

Nueva publicación

Creamos una variable con un diccionario con las partes del post: título, cuerpo del post y el usuario que ha escrito el post.

In [62]:
nueva_publicacion = {
    "title": "Mi primera publicación",
    "body": "Lorem ipsum dolor sit amet consectetur adipiscing elit donec ligula, rhoncus sapien vulputate laoreet eros hendrerit varius in.",
    "userId": 1
}

Se crea una variable que guarda la respuesta de la petición post.

In [63]:
respuesta_post = requests.post(
    url_api + "/posts",
    json=nueva_publicacion
)

Respuesta de la API a nuestra petición. En este caso 201, es decir, creado correctamente.

In [64]:
respuesta_post.status_code

201

### PATCH

Creamos una variable con un diccionario con los cambios que queremos realizar.

In [65]:
cambios = {
    "title": "Título modificado"
}

Usamos patch para hacer el cambio solo en la parte que queremos. En la url especificamos que post es exactamente.

In [66]:
cambios_post = requests.patch(
    url_api + "/posts/1",
    json=cambios
)

Verificamos que la respuesta es ok

In [67]:
cambios_post.status_code

200

Y vemos que se realiazó el post correctamente.

In [68]:
cambios_post.json()

{'userId': 1,
 'id': 1,
 'title': 'Título modificado',
 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

### DELETE

Para borrar un post debemos usar el .delete especificando en la url el post que queremos eliminar.

In [69]:
borrar_post = requests.delete(
    url_api + "/posts/1"
)

In [70]:
print("Código de estado:", borrar_post.status_code)
print("Respuesta:", borrar_post.json())

Código de estado: 200
Respuesta: {}

## NIVEL 2

Interacció amb una API pública real

## API seleccionada: MeowFacts

URL base:
https://meowfacts.herokuapp.com/

Dentro del github de la API meowfact > docs > api.jason, podemos ver un apartado dentro de "path{" con los endpoints:

- `/` → devuelve una o varias curiosidades sobre gatos.
- `/health` → comprueba si la API está activa.
- `/options` → devuelve las opciones disponibles, como los idiomas.

Tambiém podemos encontrar los parámetros:

- `factID` → permite pedir una curiosidad concreta.
- `count` → número de curiosidades que queremos recibir.
- `lang` → idioma de la respuesta.

en el apartado de responses vemos que las respuestas seran en formato json:

"application/json"

Se guarda la url en una variable, hacemos la petición con .get con dos parámetros dentro de la petición, que nos de cinco datos sobre los gatos ("counts" :5) y que sea en inglés ("lang":"eng").

Se imprime el código de estado de la petición: 200,petición funciona correctamente.

In [71]:
#GET

url_meow = "https://meowfacts.herokuapp.com/"

respuesta_meow = requests.get(
    url_meow,
    params = {
        "count":5,
        "lang" : "eng"} 
)

print("Código de estado:", respuesta_meow.status_code)

Código de estado: 200

Se convierte la respuesta que da la API a objetos de Python.
datos_meow es un diccionario, data seria la clave y la o las frases en una lista dentro de esa clave.

In [72]:
datos_meow = respuesta_meow.json()

In [73]:
datos_meow["data"]

['A cat can spend five or more hours a day grooming himself.',
 'A cats field of vision is about 185 degrees.',
 'Cats have 30 vertebrae--5 more than humans have.',
 'A cat has been mayor of Talkeetna, Alaska, for 15 years. His name is Stubbs.',
 'You check your cats pulse on the inside of the back thigh, where the leg joins to the body. Normal for cats: 110-170 beats per minute.']

Se convierte los datos en un DataFrame.

datos_meow["data"] -> lista de datos de los gatos.

columns=["fact"] -> nombre de la columna

In [74]:
df_meow = pd.DataFrame(datos_meow["data"], columns=["fact"])

Como Python me mostraba el texto cortado, pasamos el DataFRame a cadena de texto

In [75]:
print(df_meow.to_string())

                                                                                                                                     fact
0                                                                              A cat can spend five or more hours a day grooming himself.
1                                                                                            A cats field of vision is about 185 degrees.
2                                                                                        Cats have 30 vertebrae--5 more than humans have.
3                                                            A cat has been mayor of Talkeetna, Alaska, for 15 years. His name is Stubbs.
4  You check your cats pulse on the inside of the back thigh, where the leg joins to the body. Normal for cats: 110-170 beats per minute.

In [76]:
for dato in df_meow["fact"]:
    print(dato)
    print()

A cat can spend five or more hours a day grooming himself.

A cats field of vision is about 185 degrees.

Cats have 30 vertebrae--5 more than humans have.

A cat has been mayor of Talkeetna, Alaska, for 15 years. His name is Stubbs.

You check your cats pulse on the inside of the back thigh, where the leg joins to the body. Normal for cats: 110-170 beats per minute.

# NIVEL 3
API d'Open Data Barcelona

1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show. .

In [77]:
url_bcn = "https://opendata-ajuntament.barcelona.cat/data/api/3/action"

He guardado en una variable una lista de temas que me podían interesar.

Con un bucle for he hecho la petición de que hiciese una búsqueda con los parámetros que había guardado en la variable.

Convierte la respuesta de la API en objeto de Python.
y mostramos por cada parámetro de la lista los 5 primeros temas.

In [78]:
busquedas = ["poblacio", "habitatge", "accidents"]

for busqueda in busquedas:
    respuesta = requests.get(
        url_bcn + "/package_search",
        params={"q": busqueda}
    )

    print(f"\nResultados para: {busqueda}")
    
    datos = respuesta.json()

    for dataset in datos["result"]["results"][:5]:
        print(dataset["title"])

Resultados para: poblacio
Projected population by scenario and sex
Population by sex
Study of the population exposed to atmospheric pollution from the Barcelona City Resilience Atlas
Study of the population exposed to noise pollution from the Atlas of resilience of the city of Barcelona
Vulnerability of the population due to an insufficient socioeconomic situation affecting the heat wave in the city of Barcelona

Resultados para: habitatge
Area (m²) of real estate properties transmitted by sale transaction, based on notarials records, by property use
Number of real estate property transactions, based on notarial records, by property use
Households by number of females
Household by size
Households by household structure

Resultados para: accidents
Accidents by driver cause managed by the Guàrdia Urbana in the city of Barcelona
Accidents by mediate cause managed by the Guàrdia Urbana in the city of Barcelona
Accidents  by type managed by the Guàrdia Urbana in the city of Barcelona
People involved in accidents managed by the Police in the city of Barcelona
Vehicles involved in accidents handled by the police in the city of Barcelona

Después de revisar los temas, he elegido habitatge, asi que hago una nueva petición solo con los datasets de habitatge.
Se convierten en objeto Python.

In [79]:
respuesta_search = requests.get(
    url_bcn + "/package_search",
    params={"q": "habitatge"}
)

print(respuesta_search.status_code)

datos_search = respuesta_search.json()

200

Miramos la estructura dataset

In [80]:
print(datos_search.keys())

dict_keys(['help', 'success', 'result'])

In [81]:
print(datos_search["result"].keys())

dict_keys(['count', 'sort', 'facets', 'results', 'search_facets'])

Por cada dataset que hay dentro de la lista datos_search["result"]["results"], imprime su título, nombre y una linea separadora.

In [82]:
for dataset in datos_search["result"]["results"]:
    print(dataset["title"])
    print(dataset["name"])
    print("-" * 50)

Area (m²) of real estate properties transmitted by sale transaction, based on notarials records, by property use
notaris_compravendes_trans_tip_us_sup
--------------------------------------------------
Number of real estate property transactions, based on notarial records, by property use
notaris_compravendes_trans_tip_us
--------------------------------------------------
Households by number of females
pad_dom_mdbas_dones
--------------------------------------------------
Household by size
pad_dom_mdbas_n-persones
--------------------------------------------------
Households by household structure
pad_dom_mdbas_tipus-domicili
--------------------------------------------------
Average age of registered people in the household by household structure
pad_dom_mdbas_tipus-domicili_edat
--------------------------------------------------
Households by number of people under 18 years of age
pad_dom_mdbas_edat-0018
--------------------------------------------------
Households by number of people aged 18 to 64 years old
pad_dom_mdbas_edat-1864
--------------------------------------------------
Households by number of people aged 65 years old or over
pad_dom_mdbas_edat-6599
--------------------------------------------------
Households by number of males
pad_dom_mdbas_homes
--------------------------------------------------

2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

Se hace una petición a la API para obtener toda la información del dataset escogido: 

notaris_compravendes_trans_tip_us

In [83]:
respuesta_show = requests.get(
    url_bcn + "/package_show",
    params={"id": "notaris_compravendes_trans_tip_us"}
)

print(respuesta_show.status_code)

datos_show = respuesta_show.json()

200

Para cada recurso que hay dentro, imprime su nombre, el formato del archivo y el ID.

In [84]:
for recurso in datos_show["result"]["resources"]:
    print("Nombre:", recurso["name"])
    print("Formato:", recurso.get("format"))
    print("Resource ID:", recurso["id"])
    print("-" * 50)

Nombre: 2026_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 0d292f7d-0ad6-431d-8a54-6e9ad9d47ac3
--------------------------------------------------
Nombre: 2025_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 4b8c5cf6-56aa-4a64-b87f-6159a1272206
--------------------------------------------------
Nombre: 2024_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 8cef2abe-824f-48ea-8f2a-7cdb2689a6f8
--------------------------------------------------
Nombre: 2023_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: af3ad569-4f1e-4409-afb1-a760975a3519
--------------------------------------------------
Nombre: 2022_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 1e8e5128-94fe-4e9b-9a7e-edf5a28ff812
--------------------------------------------------
Nombre: 2021_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: e27e7dd8-b2c9-47ed-a43e-291e247b46a9
--------------------------------------------------
Nombre: 2020_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 6ccd5b89-8ef7-46ed-9607-ee2b70ddc8de
--------------------------------------------------
Nombre: 2019_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 05131f27-d38b-402e-8423-42a357e50890
--------------------------------------------------
Nombre: 2018_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 23cf0bcd-df4d-454c-aa55-e3c493e40e5d
--------------------------------------------------
Nombre: 2017_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: dd146ae7-36d9-4473-8065-fcf86b4578a3
--------------------------------------------------
Nombre: 2016_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 6f045df8-dd5e-4b7c-9bf8-2c8f42d9e5ea
--------------------------------------------------
Nombre: 2015_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 6d10318c-c5b9-41ed-a181-31c1e63d6440
--------------------------------------------------
Nombre: 2014_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 8dec8802-a4a2-4163-b47c-9180d5994b09
--------------------------------------------------
Nombre: 2013_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: ccfd334d-3a6e-46a5-b683-79c77504ffdc
--------------------------------------------------
Nombre: 2012_notaris_compravendes_trans_tip_us.csv
Formato: CSV
Resource ID: 6318a32b-08d1-4c39-836c-42290274843d
--------------------------------------------------

3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres

In [85]:
#Recurso seleccionado 2025

resource_id = "4b8c5cf6-56aa-4a64-b87f-6159a1272206"

Hacemos una petición con /datastore_search, para que nos dé las filas con los datos.
Pasamos el recurso concreto que queremos, en este caso 2025_notaris_compravendes_trans_tip_us.csv, con un límite de cien para que me develva cien registros.

Convertimos el JSON

In [86]:
respuesta_data = requests.get(
    url_bcn + "/datastore_search",
    params={
        "resource_id": resource_id,
        "limit": 100
    }
)

print(respuesta_data.status_code)

datos_data = respuesta_data.json()

print(datos_data.keys())
print(datos_data["result"].keys())

200
dict_keys(['help', 'success', 'result'])
dict_keys(['resource_id', 'fields', 'records', '_links', 'limit', 'total'])

In [87]:
len(datos_data["result"]["records"])

100

Dame la lista de filas que ha devuelto la API

In [88]:
datos_data["result"]["records"]

[{'Tipologia_Us_Codi': '2',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'el Raval',
  'Mes': '1',
  'Codi_Barri': '1',
  'Nombre': '..',
  '_id': 1,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'el Raval',
  'Mes': '1',
  'Codi_Barri': '1',
  'Nombre': '11',
  '_id': 2,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': 'el Raval',
  'Mes': '1',
  'Codi_Barri': '1',
  'Nombre': '..',
  '_id': 3,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'el Raval',
  'Mes': '1',
  'Codi_Barri': '1',
  'Nombre': '45',
  '_id': 4,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'el Barri Gòtic',
  'Mes': '1',
  'Codi_Barri': '2',
  'Nombre': '..',
  '_id': 5,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'el Barri Gòtic',
  'Mes': '1',
  'Codi_Barri': '2',
  'Nombre': '5',
  '_id': 6,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '8',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Equipaments',
  'Nom_Barri': 'el Barri Gòtic',
  'Mes': '1',
  'Codi_Barri': '2',
  'Nombre': '..',
  '_id': 7,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '5',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Turístic',
  'Nom_Barri': 'el Barri Gòtic',
  'Mes': '1',
  'Codi_Barri': '2',
  'Nombre': '..',
  '_id': 8,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '9',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'No consta',
  'Nom_Barri': 'el Barri Gòtic',
  'Mes': '1',
  'Codi_Barri': '2',
  'Nombre': '..',
  '_id': 9,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': 'el Barri Gòtic',
  'Mes': '1',
  'Codi_Barri': '2',
  'Nombre': '..',
  '_id': 10,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'el Barri Gòtic',
  'Mes': '1',
  'Codi_Barri': '2',
  'Nombre': '22',
  '_id': 11,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'la Barceloneta',
  'Mes': '1',
  'Codi_Barri': '3',
  'Nombre': '..',
  '_id': 12,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'la Barceloneta',
  'Mes': '1',
  'Codi_Barri': '3',
  'Nombre': '15',
  '_id': 13,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
  'Mes': '1',
  'Codi_Barri': '4',
  'Nombre': '6',
  '_id': 14,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
  'Mes': '1',
  'Codi_Barri': '4',
  'Nombre': '..',
  '_id': 15,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '1',
  'Nom_Districte': 'Ciutat Vella',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
  'Mes': '1',
  'Codi_Barri': '4',
  'Nombre': '26',
  '_id': 16,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'el Fort Pienc',
  'Mes': '1',
  'Codi_Barri': '5',
  'Nombre': '15',
  '_id': 17,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'el Fort Pienc',
  'Mes': '1',
  'Codi_Barri': '5',
  'Nombre': '..',
  '_id': 18,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': 'el Fort Pienc',
  'Mes': '1',
  'Codi_Barri': '5',
  'Nombre': '..',
  '_id': 19,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'el Fort Pienc',
  'Mes': '1',
  'Codi_Barri': '5',
  'Nombre': '32',
  '_id': 20,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'la Sagrada Família',
  'Mes': '1',
  'Codi_Barri': '6',
  'Nombre': '30',
  '_id': 21,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'la Sagrada Família',
  'Mes': '1',
  'Codi_Barri': '6',
  'Nombre': '..',
  '_id': 22,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': 'la Sagrada Família',
  'Mes': '1',
  'Codi_Barri': '6',
  'Nombre': '..',
  '_id': 23,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'la Sagrada Família',
  'Mes': '1',
  'Codi_Barri': '6',
  'Nombre': '49',
  '_id': 24,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': "la Dreta de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '7',
  'Nombre': '22',
  '_id': 25,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': "la Dreta de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '7',
  'Nombre': '7',
  '_id': 26,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '5',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Turístic',
  'Nom_Barri': "la Dreta de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '7',
  'Nombre': '..',
  '_id': 27,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': "la Dreta de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '7',
  'Nombre': '..',
  '_id': 28,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': "la Dreta de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '7',
  'Nombre': '42',
  '_id': 29,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': "l'Antiga Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '8',
  'Nombre': '12',
  '_id': 30,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': "l'Antiga Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '8',
  'Nombre': '6',
  '_id': 31,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '5',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Turístic',
  'Nom_Barri': "l'Antiga Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '8',
  'Nombre': '..',
  '_id': 32,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '6',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Solars',
  'Nom_Barri': "l'Antiga Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '8',
  'Nombre': '..',
  '_id': 33,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '6',
  'Codi_Districte': '9',
  'Nom_Districte': 'Sant Andreu',
  'Tipologia_Us_Desc': 'Solars',
  'Nom_Barri': 'Sant Andreu',
  'Mes': '12',
  'Codi_Barri': '60',
  'Nombre': '..',
  '_id': 2685,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': "l'Antiga Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '8',
  'Nombre': '5',
  '_id': 34,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': "l'Antiga Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '8',
  'Nombre': '30',
  '_id': 35,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': "la Nova Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '9',
  'Nombre': '28',
  '_id': 36,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': "la Nova Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '9',
  'Nombre': '..',
  '_id': 37,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': "la Nova Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '9',
  'Nombre': '..',
  '_id': 38,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': "la Nova Esquerra de l'Eixample",
  'Mes': '1',
  'Codi_Barri': '9',
  'Nombre': '44',
  '_id': 39,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'Sant Antoni',
  'Mes': '1',
  'Codi_Barri': '10',
  'Nombre': '13',
  '_id': 40,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'Sant Antoni',
  'Mes': '1',
  'Codi_Barri': '10',
  'Nombre': '5',
  '_id': 41,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': 'Sant Antoni',
  'Mes': '1',
  'Codi_Barri': '10',
  'Nombre': '..',
  '_id': 42,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '2',
  'Nom_Districte': 'Eixample',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'Sant Antoni',
  'Mes': '1',
  'Codi_Barri': '10',
  'Nombre': '24',
  '_id': 43,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'el Poble Sec',
  'Mes': '1',
  'Codi_Barri': '11',
  'Nombre': '10',
  '_id': 44,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'el Poble Sec',
  'Mes': '1',
  'Codi_Barri': '11',
  'Nombre': '13',
  '_id': 45,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'el Poble Sec',
  'Mes': '1',
  'Codi_Barri': '11',
  'Nombre': '48',
  '_id': 46,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'la Marina del Prat Vermell',
  'Mes': '1',
  'Codi_Barri': '12',
  'Nombre': '16',
  '_id': 47,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'la Marina del Prat Vermell',
  'Mes': '1',
  'Codi_Barri': '12',
  'Nombre': '8',
  '_id': 48,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'la Marina de Port',
  'Mes': '1',
  'Codi_Barri': '13',
  'Nombre': '11',
  '_id': 49,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'la Marina de Port',
  'Mes': '1',
  'Codi_Barri': '13',
  'Nombre': '5',
  '_id': 50,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'la Marina de Port',
  'Mes': '1',
  'Codi_Barri': '13',
  'Nombre': '23',
  '_id': 51,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'la Font de la Guatlla',
  'Mes': '1',
  'Codi_Barri': '14',
  'Nombre': '..',
  '_id': 52,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'la Font de la Guatlla',
  'Mes': '1',
  'Codi_Barri': '14',
  'Nombre': '6',
  '_id': 53,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'la Font de la Guatlla',
  'Mes': '1',
  'Codi_Barri': '14',
  'Nombre': '6',
  '_id': 54,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'Hostafrancs',
  'Mes': '1',
  'Codi_Barri': '15',
  'Nombre': '..',
  '_id': 55,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'Hostafrancs',
  'Mes': '1',
  'Codi_Barri': '15',
  'Nombre': '..',
  '_id': 56,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '9',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'No consta',
  'Nom_Barri': 'Hostafrancs',
  'Mes': '1',
  'Codi_Barri': '15',
  'Nombre': '..',
  '_id': 57,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'Hostafrancs',
  'Mes': '1',
  'Codi_Barri': '15',
  'Nombre': '..',
  '_id': 58,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'la Bordeta',
  'Mes': '1',
  'Codi_Barri': '16',
  'Nombre': '5',
  '_id': 59,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'la Bordeta',
  'Mes': '1',
  'Codi_Barri': '16',
  'Nombre': '..',
  '_id': 60,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'la Bordeta',
  'Mes': '1',
  'Codi_Barri': '16',
  'Nombre': '12',
  '_id': 61,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'Sants - Badal',
  'Mes': '1',
  'Codi_Barri': '17',
  'Nombre': '10',
  '_id': 62,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'Sants - Badal',
  'Mes': '1',
  'Codi_Barri': '17',
  'Nombre': '..',
  '_id': 63,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'Sants - Badal',
  'Mes': '1',
  'Codi_Barri': '17',
  'Nombre': '14',
  '_id': 64,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'Sants',
  'Mes': '1',
  'Codi_Barri': '18',
  'Nombre': '14',
  '_id': 65,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'Sants',
  'Mes': '1',
  'Codi_Barri': '18',
  'Nombre': '..',
  '_id': 66,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '6',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Solars',
  'Nom_Barri': 'Sants',
  'Mes': '1',
  'Codi_Barri': '18',
  'Nombre': '..',
  '_id': 67,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '3',
  'Nom_Districte': 'Sants-Montjuïc',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'Sants',
  'Mes': '1',
  'Codi_Barri': '18',
  'Nombre': '29',
  '_id': 68,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'les Corts',
  'Mes': '1',
  'Codi_Barri': '19',
  'Nombre': '23',
  '_id': 69,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'les Corts',
  'Mes': '1',
  'Codi_Barri': '19',
  'Nombre': '..',
  '_id': 70,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': 'les Corts',
  'Mes': '1',
  'Codi_Barri': '19',
  'Nombre': '10',
  '_id': 71,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'les Corts',
  'Mes': '1',
  'Codi_Barri': '19',
  'Nombre': '27',
  '_id': 72,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'la Maternitat i Sant Ramon',
  'Mes': '1',
  'Codi_Barri': '20',
  'Nombre': '12',
  '_id': 73,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '3',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Comercial',
  'Nom_Barri': 'la Maternitat i Sant Ramon',
  'Mes': '1',
  'Codi_Barri': '20',
  'Nombre': '..',
  '_id': 74,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '4',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Oficina',
  'Nom_Barri': 'la Maternitat i Sant Ramon',
  'Mes': '1',
  'Codi_Barri': '20',
  'Nombre': '..',
  '_id': 75,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'la Maternitat i Sant Ramon',
  'Mes': '1',
  'Codi_Barri': '20',
  'Nombre': '14',
  '_id': 76,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'Pedralbes',
  'Mes': '1',
  'Codi_Barri': '21',
  'Nombre': '8',
  '_id': 77,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '4',
  'Nom_Districte': 'Les Corts',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'Pedralbes',
  'Mes': '1',
  'Codi_Barri': '21',
  'Nombre': '12',
  '_id': 78,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '2',
  'Codi_Districte': '5',
  'Nom_Districte': 'Sarrià-Sant Gervasi',
  'Tipologia_Us_Desc': 'Aparcament',
  'Nom_Barri': 'Vallvidrera, el Tibidabo i les Planes',
  'Mes': '1',
  'Codi_Barri': '22',
  'Nombre': '..',
  '_id': 79,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '6',
  'Codi_Districte': '5',
  'Nom_Districte': 'Sarrià-Sant Gervasi',
  'Tipologia_Us_Desc': 'Solars',
  'Nom_Barri': 'Vallvidrera, el Tibidabo i les Planes',
  'Mes': '1',
  'Codi_Barri': '22',
  'Nombre': '..',
  '_id': 80,
  'Any': '2025'},
 {'Tipologia_Us_Codi': '1',
  'Codi_Districte': '5',
  'Nom_Districte': 'Sarrià-Sant Gervasi',
  'Tipologia_Us_Desc': 'Residencial',
  'Nom_Barri': 'Vallvidrera, el Tibidabo i les Planes',

4. Converteix els resultats a un DataFrame.

In [89]:
df_habitatge = pd.DataFrame(
    datos_data["result"]["records"]
)

df_habitatge.head()

,Tipologia_Us_Codi,Codi_Districte,Nom_Districte,Tipologia_Us_Desc,Nom_Barri,Mes,Codi_Barri,Nombre,_id,Any
0,2,1,Ciutat Vella,Aparcament,el Raval,1,1,..,1,2025
1,3,1,Ciutat Vella,Comercial,el Raval,1,1,11,2,2025
2,4,1,Ciutat Vella,Oficina,el Raval,1,1,..,3,2025
3,1,1,Ciutat Vella,Residencial,el Raval,1,1,45,4,2025
4,2,1,Ciutat Vella,Aparcament,el Barri Gòtic,1,2,..,5,2025

5. Desa el DataFrame en un fitxer .csv.

In [90]:
df_habitatge.to_csv(
    "habitatge_barcelona_2025.csv",
    index=False
)

print("Archivo guardado correctamente")

Archivo guardado correctamente