In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\herre\OneDrive\Desktop\Proyectos DATA\SPRINT 13"
)

RAW_POBLACION = (
    PROJECT_ROOT
    / "01_data"
    / "01_raw"
    / "indicadores sociales"
    / "poblacion"
)

PROCESSED_POBLACION = (
    PROJECT_ROOT
    / "01_data"
    / "02_processed"
    / "indicadores_sociales"
    / "poblacion"
)

PROCESSED_POBLACION.mkdir(parents=True, exist_ok=True)

In [2]:
ruta_entrada = RAW_POBLACION / "56940.csv"

poblacion = pd.read_csv(
    ruta_entrada,
    sep=";",
    encoding="latin1"
)

poblacion.head()

,Edad simple,Comunidades y ciudades autónomas,Sexo,Periodo,Total
0,Todas las edades,Total Nacional,Total,1 de enero de 2025,49.128.297
1,Todas las edades,Total Nacional,Total,1 de octubre de 2024,48.999.880
2,Todas las edades,Total Nacional,Total,1 de julio de 2024,48.821.936
3,Todas las edades,Total Nacional,Total,1 de abril de 2024,48.701.130
4,Todas las edades,Total Nacional,Total,1 de enero de 2024,48.619.695

In [3]:
poblacion_filtrada = poblacion[
    (poblacion['Periodo'].str.startswith('1 de enero')) &
    (poblacion['Comunidades y ciudades autónomas'] != 'Total Nacional')
].copy()

poblacion_filtrada.head()

,Edad simple,Comunidades y ciudades autónomas,Sexo,Periodo,Total
45,Todas las edades,01 Andalucía,Total,1 de enero de 2025,8.676.713
49,Todas las edades,01 Andalucía,Total,1 de enero de 2024,8.631.862
53,Todas las edades,01 Andalucía,Total,1 de enero de 2023,8.584.147
57,Todas las edades,01 Andalucía,Total,1 de enero de 2022,8.511.167
61,Todas las edades,01 Andalucía,Total,1 de enero de 2021,8.484.804

In [4]:
poblacion_filtrada.shape

(228, 5)

In [5]:
poblacion_filtrada['comunidad'] = (
    poblacion_filtrada['Comunidades y ciudades autónomas']
    .str.replace(r'^\d+\s+', '', regex=True)
)

poblacion_filtrada[['Comunidades y ciudades autónomas', 'comunidad']].drop_duplicates()

    Comunidades y ciudades autónomas                    comunidad
45                      01 Andalucía                    Andalucía
90                         02 Aragón                       Aragón
135       03 Asturias, Principado de      Asturias, Principado de
180                04 Balears, Illes               Balears, Illes
225                      05 Canarias                     Canarias
270                     06 Cantabria                    Cantabria
315               07 Castilla y León              Castilla y León
360          08 Castilla - La Mancha         Castilla - La Mancha
405                      09 Cataluña                     Cataluña
450          10 Comunitat Valenciana         Comunitat Valenciana
495                   11 Extremadura                  Extremadura
540                       12 Galicia                      Galicia
585          13 Madrid, Comunidad de         Madrid, Comunidad de
630             14 Murcia, Región de            Murcia, Región de
675   15 Navarra, Comunidad Foral de  Navarra, Comunidad Foral de
720                    16 País Vasco                   País Vasco
765                     17 Rioja, La                    Rioja, La
810                         18 Ceuta                        Ceuta
855                       19 Melilla                      Melilla

In [6]:
mapa_comunidades = {
    'Asturias, Principado de': 'Asturias',
    'Balears, Illes': 'Baleares',
    'Castilla - La Mancha': 'Castilla-La Mancha',
    'Comunitat Valenciana': 'Comunidad Valenciana',
    'Madrid, Comunidad de': 'Madrid',
    'Murcia, Región de': 'Murcia',
    'Navarra, Comunidad Foral de': 'Navarra',
    'Rioja, La': 'La Rioja'
}

poblacion_filtrada['comunidad'] = (
    poblacion_filtrada['comunidad']
    .replace(mapa_comunidades)
)

In [7]:
poblacion_filtrada['comunidad'].unique()

array(['Andalucía', 'Aragón', 'Asturias', 'Baleares', 'Canarias',
       'Cantabria', 'Castilla y León', 'Castilla-La Mancha', 'Cataluña',
       'Comunidad Valenciana', 'Extremadura', 'Galicia', 'Madrid',
       'Murcia', 'Navarra', 'País Vasco', 'La Rioja', 'Ceuta', 'Melilla'],
      dtype=object)

In [8]:
poblacion_filtrada['año'] = (
    poblacion_filtrada['Periodo']
    .str.extract(r'(\d{4})')
    .astype(int)
)

poblacion_filtrada[['Periodo', 'año']].head()

               Periodo   año
45  1 de enero de 2025  2025
49  1 de enero de 2024  2024
53  1 de enero de 2023  2023
57  1 de enero de 2022  2022
61  1 de enero de 2021  2021

In [9]:
poblacion_final = poblacion_filtrada[
    ['comunidad', 'año', 'Total']
].copy()

poblacion_final = poblacion_final.rename(
    columns={'Total': 'poblacion'}
)

poblacion_final.head()

    comunidad   año  poblacion
45  Andalucía  2025  8.676.713
49  Andalucía  2024  8.631.862
53  Andalucía  2023  8.584.147
57  Andalucía  2022  8.511.167
61  Andalucía  2021  8.484.804

In [10]:
poblacion_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 228 entries, 45 to 899
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   comunidad  228 non-null    object
 1   año        228 non-null    int64
 2   poblacion  228 non-null    object
dtypes: int64(1), object(2)
memory usage: 7.1+ KB

In [11]:
poblacion_final['poblacion'] = (
    poblacion_final['poblacion']
    .str.replace('.', '', regex=False)
    .astype(int)
)

In [12]:
poblacion_final.describe()

               año     poblacion
count   228.000000  2.280000e+02
mean   2019.500000  2.488775e+06
std       3.459648  2.508009e+06
min    2014.000000  8.305100e+04
25%    2016.750000  6.702448e+05
50%    2019.500000  1.500194e+06
75%    2022.250000  2.699620e+06
max    2025.000000  8.676713e+06

In [13]:
ruta_salida = PROCESSED_POBLACION / "poblacion.csv"

poblacion_final.to_csv(
    ruta_salida,
    index=False
)

print(f"Archivo guardado en: {ruta_salida}")

Archivo guardado en: C:\Users\herre\OneDrive\Desktop\Proyectos DATA\SPRINT 13\01_data\02_processed\indicadores_sociales\poblacion\poblacion.csv