In [18]:
import pandas as pd

dist_inmigracion2015 = pd.read_csv(
    r'c:\Users\herre\OneDrive\Desktop\IT ACADEMY\ESPECIALIDAD\EJERCICICIOS\SPRINT 13\PRENSA\PROCESADOS\inmigracion_2015_con_texto.csv'
)
dist_inmigracion2016 = pd.read_csv(
    r'c:\Users\herre\OneDrive\Desktop\IT ACADEMY\ESPECIALIDAD\EJERCICICIOS\SPRINT 13\PRENSA\PROCESADOS\inmigracion_2016_con_texto.csv'
)
dist_inmigracion2019 = pd.read_csv(
    r'c:\Users\herre\OneDrive\Desktop\IT ACADEMY\ESPECIALIDAD\EJERCICICIOS\SPRINT 13\PRENSA\PROCESADOS\inmigracion_2019_con_texto.csv'
)
dist_inmigracion2023 = pd.read_csv(
    r'c:\Users\herre\OneDrive\Desktop\IT ACADEMY\ESPECIALIDAD\EJERCICICIOS\SPRINT 13\PRENSA\PROCESADOS\inmigracion_2023_con_texto.csv'
)

In [14]:
print(dist_inmigracion2015.shape)

(14333, 10)

In [15]:
dist_inmigracion2015.head()

,id,publish_date,media_name,media_url,title,url,language,anio,mes,texto
0,50859f6f441e40d325df5f31d22369451c2bc5a02fd23b...,2015-02-11,diariojaen.es,diariojaen.es,Golpe a la inmigraciÃ³n clandestina,https://www.diariojaen.es/historico/golpe-a-la...,es,2015,2,Golpe a la inmigración clandestina\nContra los...
1,73033c3fd29d8952fc066c6c9295ad46dfcb7621568fad...,2015-01-09,diariojaen.es,diariojaen.es,Los Reyes Magos van en patera,https://www.diariojaen.es/historico/los-reyes-...,es,2015,1,Los Reyes Magos van en patera\nAquellos vetust...
2,c8a983e636022993dd991c2d7e5ba58f378944c76aa3a7...,2015-02-16,diariojaen.es,diariojaen.es,Cae de manera drÃ¡stica la contrataciÃ³n de in...,https://www.diariojaen.es/historico/cae-de-man...,es,2015,2,Cae de manera drástica la contratación de inmi...
3,d25f31e8b090909033d70dfaa3a6abc224781f4783a16c...,2015-04-22,diariojaen.es,diariojaen.es,La tragedia de la inmigraciÃ³n,https://www.diariojaen.es/historico/la-tragedi...,es,2015,4,La tragedia de la inmigración\nEl reciente nau...
4,da0cd33371a533d51bbf141da1d3bb7606a1088a50fc0f...,2015-03-12,diariojaen.es,diariojaen.es,Hablando de inmigraciÃ³n,https://www.diariojaen.es/historico/hablando-d...,es,2015,3,Hablando de inmigración\nHace ya muchos siglos...

In [16]:
dist_inmigracion2015.columns.tolist()

['id',
 'publish_date',
 'media_name',
 'media_url',
 'title',
 'url',
 'language',
 'anio',
 'mes',
 'texto']

In [17]:
dist_inmigracion2015['media_name'].value_counts().head(20)

media_name
abc.es                        1160
eldia.es                       820
rtve.es                        818
elperiodico.com                808
canarias7.es                   633
antena3.com                    614
elmundo.es                     563
elpais.com                     560
elperiodicoextremadura.com     451
heraldo.es                     447
publico.es                     392
lavozdegalicia.es              376
europapress.es                 362
europasur.es                   338
diariodenavarra.es             300
farodevigo.es                  296
elconfidencial.com             279
ondacero.es                    267
lacerca.com                    242
eldiariomontanes.es            219
Name: count, dtype: int64

In [19]:
abc = dist_inmigracion[
    dist_inmigracion['media_name'] == 'abc.es'
]

abc[['publish_date','title','url']].head(5)

,publish_date,title,url
36,2015-01-01,Otros 54 inmigrantes logran entrar en Melilla,http://kioskoymas.abc.es/noticias/espana/20150...
63,2015-01-02,Un carguero con mÃ¡s de 400 inmigrantes y sin ...,http://www.abc.es/internacional/20150102/abci-...
67,2015-01-02,Leve repunte de la inmigración clandestina dur...,http://kioskoymas.abc.es/noticias/espana/20150...
77,2015-01-03,La PolicÃ­a despide entre aplausos al agente m...,http://www.abc.es/madrid/20150103/abci-funeral...
78,2015-01-02,"El inmigrante, al policÃ­a muerto en Embajador...",http://www.abc.es/madrid/20150103/abci-gritos-...

In [20]:
dist_inmigracion['url'].str.contains(
    'kioskoymas',
    na=False
).mean() * 100

np.float64(1.4930579780925137)

In [21]:
abc = dist_inmigracion[
    (dist_inmigracion['media_name'] == 'abc.es')
    &
    (~dist_inmigracion['url'].str.contains('kioskoymas', na=False))
]

abc[['publish_date', 'title', 'url']].sample(
    10,
    random_state=42
)

,publish_date,title,url
3915,2015-09-02,Once refugiados sirios mueren ahogados al inte...,http://www.abc.es/internacional/20150902/abci-...
338,2015-02-06,Salvamento MarÃ­timo busca a los ocupantes de ...,http://www.abc.es/espana/20150206/abci-buscan-...
12150,2015-12-18,España ha recibido 13.000 solicitudes de asilo...,http://sevilla.abc.es/espana/abci-espana-recib...
5065,2015-09-10,La PolicÃ­a danesa permite a los refugiados di...,http://www.abc.es/internacional/20150910/abci-...
853,2015-04-05,Seis inmigrantes han saltado el vallado de Ceu...,http://www.abc.es/espana/20150405/abci-inmigra...
6391,2015-09-23,"No hay cuotas obligatorias, y otras claves del...",http://www.abc.es/internacional/20150923/abci-...
13963,2015-10-30,Un grupo de refugiados se niega a bajarse del ...,http://sevilla.abc.es/internacional/abci-grupo...
653,2015-03-11,Localizan a 18 supervivientes y 4 cadÃ¡veres d...,http://www.abc.es/espana/20150311/abci-inmigra...
5652,2015-09-15,Alemania amenaza con reducir fondos estructura...,http://www.abc.es/internacional/20150915/abci-...
9398,2015-09-29,Alemania prevé que en 2016 lleguen a sus front...,https://www.abc.es/internacional/20150929/abci...

In [22]:
candidatos = [
    'elmundo.es',
    'elpais.com',
    'elperiodico.com',
    'publico.es',
    'elconfidencial.com'
]

muestra = (
    dist_inmigracion[
        dist_inmigracion['media_name'].isin(candidatos)
    ]
    .groupby('media_name', group_keys=False)
    .sample(3, random_state=42)
)

muestra[['media_name', 'publish_date', 'title', 'url']]

,media_name,publish_date,title,url
2104,elconfidencial.com,2015-06-16,Crisis entre Italia y Francia por la inmigraci...,http://www.elconfidencial.com/mundo/2015-06-16...
6031,elconfidencial.com,2015-09-18,Florentino Pérez recibió en el Bernabéu al ref...,http://www.elconfidencial.com/deportes/futbol/...
8512,elconfidencial.com,2015-12-08,"Los clubes de fútbol europeos recaudan 1,3 mil...",http://www.elconfidencial.com/deportes/futbol/...
5603,elmundo.es,2015-09-15,HungrÃ­a extenderÃ¡ la valla antirefugiados ha...,http://www.elmundo.es/internacional/2015/09/15...
5161,elmundo.es,2015-09-10,"Mariano Rajoy, sobre la crisis de los refugiad...",http://www.elmundo.es/espana/2015/09/10/55f12e...
1054,elmundo.es,2015-04-20,La UE aborda el drama migratorio tras otro nau...,http://www.elmundo.es/internacional/2015/04/20...
420,elpais.com,2015-02-11,Desaparecidos cerca de 300 inmigrantes en el C...,http://elpais.com/internacional/2015/02/11/act...
3420,elpais.com,2015-08-25,Merkel visita un centro de refugiados por prim...,http://elpais.com/internacional/2015/08/25/act...
3576,elpais.com,2015-08-28,Un barco con cientos de migrantes se hunde fre...,http://elpais.com/internacional/2015/08/28/act...
3215,elperiodico.com,2015-08-22,Localizados al menos 18 barcos con 2.000 inmig...,http://www.elperiodico.com/es/noticias/interna...
4435,elperiodico.com,2015-09-05,Austria prevÃ© recibir hoy 10.000 refugiados p...,http://www.elperiodico.com/es/noticias/interna...
4851,elperiodico.com,2015-09-10,Juncker exige pasar a la acciÃ³n ante la ola d...,http://www.elperiodico.com/es/noticias/interna...
5925,publico.es,2015-09-17,La Eurocámara da su respaldo a la reubicación ...,http://www.publico.es/internacional/eurocamara...
11852,publico.es,2015-09-03,Bruselas insta a los Estados de la UE a acoger...,http://www.publico.es/internacional/bruselas-i...
1756,publico.es,2015-05-21,Antirredadas denuncian que Interior camufla lo...,http://www.publico.es/sociedad/antirredadas-de...

In [23]:
dist_inmigracion['media_name'].value_counts().head(30)

media_name
abc.es                         1160
eldia.es                        820
rtve.es                         818
elperiodico.com                 808
canarias7.es                    633
antena3.com                     614
elmundo.es                      563
elpais.com                      560
elperiodicoextremadura.com      451
heraldo.es                      447
publico.es                      392
lavozdegalicia.es               376
europapress.es                  362
europasur.es                    338
diariodenavarra.es              300
farodevigo.es                   296
elconfidencial.com              279
ondacero.es                     267
lacerca.com                     242
eldiariomontanes.es             219
elperiodicomediterraneo.com     210
diariocordoba.com               190
elcorreo.com                    182
diariodelaltoaragon.es          175
ideal.es                        166
levante-emv.com                 161
laopinioncoruna.es              161
diariodesevilla.es              156
que.es                          150
noticiasdenavarra.com           147
Name: count, dtype: int64

In [26]:
candidatos2 = [
    'lavozdegalicia.es',
    'farodevigo.es',
    'diariodenavarra.es'
]

muestra = (
    dist_inmigracion[
        dist_inmigracion['media_name'].isin(candidatos2)
    ]
    .groupby('media_name', group_keys=False)
    .sample(3, random_state=42)
)

muestra[['media_name', 'publish_date', 'title', 'url']]

,media_name,publish_date,title,url
10828,diariodenavarra.es,2015-09-01,"​Rajoy dispuesto, con condiciones, a que Españ...",http://www.diariodenavarra.es/noticias/mas_act...
10891,diariodenavarra.es,2015-10-22,Eslovenia recibe en un día a 12.600 refugiados...,http://www.diariodenavarra.es/noticias/mas_act...
10777,diariodenavarra.es,2015-10-14,Ser español será más caro y más difícil para l...,http://www.diariodenavarra.es/noticias/mas_act...
10007,farodevigo.es,2015-09-04,LalÃ­n crearÃ¡ un registro para la acogida de ...,http://www.farodevigo.es/portada-deza-tabeiros...
10144,farodevigo.es,2015-11-27,Los familiares de Aylan logran asilo en CanadÃ¡,http://www.farodevigo.es/mundo/2015/11/27/fami...
9981,farodevigo.es,2015-06-26,"El Consejo Europeo, con un ojo puesto en Greci...",http://www.farodevigo.es/mundo/2015/06/26/cons...
12945,lavozdegalicia.es,2015-11-09,Nuevas discrepancias en el Gobierno alemÃ¡n tr...,http://www.lavozdegalicia.es/noticia/internaci...
12913,lavozdegalicia.es,2015-03-02,Un total de 15.000 niÃ±os refugiados accederÃ¡...,http://www.lavozdegalicia.es/noticia/educacion...
13054,lavozdegalicia.es,2015-09-11,Denuncian el trato Â«como animalesÂ» a los ref...,http://www.lavozdegalicia.es/noticia/internaci...